name: ADF Release Pipeline

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  release:
    environment: production
    runs-on: ubuntu-latest     
    steps:        
      - name: Download Release Asset
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: ${{ github.repository }}
          version: latest
          file: adfexport.zip
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create export directory
        run: mkdir -p ${{ github.workspace }}/export

      - name: Unzip Artifact
        run: |
          unzip adfexport.zip
          # Find and move files to the correct location
          find . -name "ARMTemplateForFactory.json" -exec cp {} ${{ github.workspace }}/ARMTemplateForFactory.json \;
          find . -name "ARMTemplateParametersForFactory.json" -exec cp {} ${{ github.workspace }}/ARMTemplateParametersForFactory.json \;
      - name: Fix File Paths
        run: |
          mv ${{ github.workspace }}/export/home/runner/work/ADF-Git2/ADF-Git2/build/export/* ${{ github.workspace }}/export/
          rm -rf ${{ github.workspace }}/export/home
          
      - name: Debug - List Files
        run: |
          echo "Current directory contents:"
          ls -la
          echo "Workspace contents:"
          ls -la ${{ github.workspace }}
          
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
          
      - name: Deploy to Dev Data Factory
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: ${{ secrets.RESOURCE_GROUP }}
          dataFactoryName: ${{ secrets.DATA_FACTORY_NAME }}
          armTemplateFile: ${{ github.workspace }}/export/ARMTemplateForFactory.json
          armTemplateParametersFile: ${{ github.workspace }}/export/ARMTemplateParametersForFactory.json
