name: ADF Release Pipeline

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  release:
    environment: production
    runs-on: ubuntu-latest     
    steps:  
      - name: Get Latest Release Artifact Name
        run: echo "LATEST_ARTIFACT=$(gh release view --json assets --jq '.assets[].name' | grep 'adfexport-')" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Download Release Asset
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: ${{ github.repository }}
          version: latest
          file: ${{ env.LATEST_ARTIFACT }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create export directory
        run: mkdir -p ${{ github.workspace }}/export

      - name: Unzip and Move Files
        run: |
          unzip ${{ env.LATEST_ARTIFACT }}
          mv home/runner/work/ADF-Git2/ADF-Git2/build/export/* ${{ github.workspace }}/export/
          rm -rf home
          
      - name: Debug - List Files
        run: |
          echo "Current directory contents:"
          ls -la
          echo "Workspace contents:"
          ls -la ${{ github.workspace }}/export
          
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
          
      - name: Deploy to Dev Data Factory
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: ${{ secrets.RESOURCE_GROUP }}
          dataFactoryName: ${{ secrets.DATA_FACTORY_NAME }}
          armTemplateFile: ${{ github.workspace }}/export/ARMTemplateForFactory.json
          armTemplateParametersFile: ${{ github.workspace }}/export/ARMTemplateParametersForFactory.json
