name: ADF Release Pipeline

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  release:
    environment: production
    runs-on: ubuntu-latest     
    steps:  
      - name: Authenticate GitHub CLI
        run: gh auth status || gh auth login --with-token <<< "${{ secrets.GH_PAT }}"
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}

      - name: Get Latest Artifact Name
        run: |
          ARTIFACT_NAME=$(gh release view --repo "${{ github.repository }}" --json assets --jq '.assets[].name' | grep 'adfexport-' | tail -n 1)
          if [ -z "$ARTIFACT_NAME" ]; then
            echo "Error: No artifact found with name pattern 'adfexport-*'." >&2
            exit 1
          fi
          echo "ARTIFACT_NAME=${ARTIFACT_NAME}" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}

      - name: Download Release Asset
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: ${{ github.repository }}
          version: latest
          file: ${{ env.ARTIFACT_NAME }}
          token: ${{ secrets.GH_PAT }}


      - name: Create export directory
        run: mkdir -p ${{ github.workspace }}/export

      - name: Unzip and Move Files
        run: |
          unzip ${{ env.ARTIFACT_NAME }}
          mv home/runner/work/ADF-Git2/ADF-Git2/build/export/* ${{ github.workspace }}/export/
          rm -rf home

          
      - name: Debug - List Files
        run: |
          echo "Current directory contents:"
          ls -la
          echo "Workspace contents:"
          ls -la ${{ github.workspace }}/export
          
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
          
      - name: Deploy to Dev Data Factory
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: ${{ secrets.RESOURCE_GROUP }}
          dataFactoryName: ${{ secrets.DATA_FACTORY_NAME }}
          armTemplateFile: ${{ github.workspace }}/export/ARMTemplateForFactory.json
          armTemplateParametersFile: ${{ github.workspace }}/export/ARMTemplateParametersForFactory.json
